### Setup

In [2]:
from cvxpy import *
import numpy as np

### Parameters

In [3]:
gamma = 0.95
alpha = 0.2
beta = 0.9048
dbeta = 0.54

### First example

Basis functions: $v_{w}(x) = \sum_{i=1}^{n} w_{1} + w_{2}\textbf{1}(x_{i}=H)$

Reward: $R(x,a,x')= \sum_{i=1}^{n} \textbf{1}(x'_{i} = H)(1-\alpha f'_{i})$

In [4]:
phi = Variable()
w = Variable(2)

objective = Minimize(phi)
constraints = []
constraints += [phi >= 0]
constraints += [phi >=  gamma*w[0] - w[0]]
constraints += [phi >= -gamma*w[0] + w[0]]

for j in range(3**4):
    xj = np.base_repr(j,base=3).zfill(4)
    fi = xj.count('1')
    hi = xj.count('0')
    
    fj = {}
    for idx in range(4):
        fj[idx] = 0
        
    if hi == 0:
        fj_sum = 0
        for a in range(fi+1):
            if a == 0:
                constraints += [phi >= w[0]+w[1] - (1-alpha*fi)*(1-alpha*(alpha*fj_sum + fi*beta - a*dbeta))-gamma*w[0]-gamma*w[1]*(1-alpha*fi)]

            constraints += [phi >= -w[0]-w[1] + (1-alpha*fi)*(1-alpha*(alpha*fj_sum + fi*beta - a*dbeta))+gamma*w[0]+gamma*w[1]*(1-alpha*fi)]
            
    if hi == 1:
        for c in range(4):
            fj_sum = c
            
            for a in range(fi+1):
                if a == 0:
                    constraints += [phi >= w[0]+w[1] - (1-alpha*fi)*(1-alpha*(alpha*fj_sum + fi*beta - a*dbeta))-gamma*w[0]-gamma*w[1]*(1-alpha*fi)]

                constraints += [phi >= -w[0]-w[1] + (1-alpha*fi)*(1-alpha*(alpha*fj_sum + fi*beta - a*dbeta))+gamma*w[0]+gamma*w[1]*(1-alpha*fi)]
            
    if hi == 2:
        for c1 in range(4):
            for c2 in range(4):
                fj_sum = c1+c2
                
                for a in range(fi+1):
                    if a == 0:
                        constraints += [phi >= w[0]+w[1] - (1-alpha*fi)*(1-alpha*(alpha*fj_sum + fi*beta - a*dbeta))-gamma*w[0]-gamma*w[1]*(1-alpha*fi)]

                    constraints += [phi >= -w[0]-w[1] + (1-alpha*fi)*(1-alpha*(alpha*fj_sum + fi*beta - a*dbeta))+gamma*w[0]+gamma*w[1]*(1-alpha*fi)]
                        
    if hi >= 3:
        for k in range(2**8):
            xk = np.base_repr(k, base=2).zfill(8)
            fj[0] = xk[0:3].count('1')
            fj[1] = xk[2:5].count('1')
            fj[2] = xk[4:7].count('1')
            fj[3] = xk[6:8].count('1') + (xk[0]=='1')
            
            fj_sum = sum(fj.values())
            for a in range(fi+1):
                if a == 0:
                    constraints += [phi >= w[0]+w[1] - (1-alpha*fi)*(1-alpha*(alpha*fj_sum + fi*beta - a*dbeta))-gamma*w[0]-gamma*w[1]*(1-alpha*fi)]

                constraints += [phi >= -w[0]-w[1] + (1-alpha*fi)*(1-alpha*(alpha*fj_sum + fi*beta - a*dbeta))+gamma*w[0]+gamma*w[1]*(1-alpha*fi)]

#     for a in range(fi+1):
#         if hi == 1:
#             for cnt in range(4):
#                 #fj[0] = cnt

#                 fj_sum = cnt
#                 constraints += [phi >=  (1-alpha*fi)*(1-alpha*(alpha*fj_sum + fi*beta - a*dbeta)) + 
#                                 gamma*w[1]*(1-alpha*fi) + gamma*w[0] - w[1] - w[0]]
#                 if a == 0:
#                     constraints += [phi >= -(1-alpha*fi)*(1-alpha*(alpha*fj_sum + fi*beta - a*dbeta)) -
#                                     gamma*w[1]*(1-alpha*fi) - gamma*w[0] + w[1] + w[0]]

#         elif hi == 2:
#             for cnt1 in range(4):
#                 fj[0] = cnt1
#                 for cnt2 in range(4):
#                     fj[1] = cnt2    

#                     fj_sum = sum(fj.values())
#                     constraints += [phi >=  (1-alpha*fi)*(1-alpha*(alpha*fj_sum + fi*beta - a*dbeta)) + 
#                                     gamma*w[1]*(1-alpha*fi) + gamma*w[0] - w[1] - w[0]]
#                     if a == 0:
#                         constraints += [phi >= -(1-alpha*fi)*(1-(alpha**2)*fj_sum - alpha*fi*beta + alpha*a*dbeta) -
#                                         gamma*w[1]*(1-alpha*fi) - gamma*w[0] + w[1] + w[0]]

#         elif hi == 3:
#             for k in range(2**7):
#                 xk = np.base_repr(k, base=2).zfill(8)
#                 fj[0] = xk[0:3].count('1')
#                 fj[1] = xk[2:5].count('1')
#                 fj[2] = xk[4:7].count('1')

#                 fj_sum = sum(fj.values())
#                 constraints += [phi >=  (1-alpha*fi)*(1-alpha*(alpha*fj_sum + fi*beta - a*dbeta)) + 
#                                 gamma*w[1]*(1-alpha*fi) + gamma*w[0] - w[1] - w[0]]
#                 if a == 0:
#                     constraints += [phi >= -(1-alpha*fi)*(1-(alpha**2)*fj_sum - alpha*fi*beta + alpha*a*dbeta) -
#                                     gamma*w[1]*(1-alpha*fi) - gamma*w[0] + w[1] + w[0]]

#         elif hi == 4:
#             for k in range(2**8):
#                 xk = np.base_repr(k, base=2).zfill(8)
#                 fj[0] = xk[0:3].count('1')
#                 fj[1] = xk[2:5].count('1')
#                 fj[2] = xk[4:7].count('1')
#                 fj[3] = xk[6:8].count('1') + xk[0].count('1')

#                 fj_sum = sum(fj.values())
#                 constraints += [phi >=  (1-alpha*fi)*(1-alpha*(alpha*fj_sum + fi*beta - a*dbeta)) + 
#                                 gamma*w[1]*(1-alpha*fi) + gamma*w[0] - w[1] - w[0]]
#                 if a == 0:
#                     constraints += [phi >= -(1-alpha*fi)*(1-(alpha**2)*fj_sum - alpha*fi*beta + alpha*a*dbeta) -
#                                     gamma*w[1]*(1-alpha*fi) - gamma*w[0] + w[1] + w[0]]

problem = Problem(objective, constraints)
print("number of constraints: %d" %len(constraints))

number of constraints: 7299


In [5]:
result = problem.solve()
print("problem status: %s" %problem.status)
print("error: %0.4f" %problem.value)
print("weight(s): ")
print(w.value)

problem status: optimal
error: 0.4983
weight(s): 
[[9.96590617]
 [0.06818765]]


In [6]:
phi = Variable()
w = Variable(2)

objective = Minimize(phi)
constraints = []
constraints += [phi >=  w[0] - gamma*w[0]]
constraints += [phi >= -w[0] + gamma*w[0]]

for j in range(3**4): 
    xj = np.base_repr(j, base=3).zfill(4)
    fi = xj.count('1')
    hi = xj.count('0')

    for k in range(2**8):
        xk = np.base_repr(k, base=2).zfill(8)

        fj = {}
        for j_ind in range(4):
            fj[j_ind] = 0
        fj[0] = xk[0:2].count('1') + xk[7].count('1')
        fj[1] = xk[1:4].count('1')
        fj[2] = xk[3:6].count('1')
        fj[3] = xk[5:8].count('1')
        
        sm_base = fi*beta
        for idx in range(4):
            sm_base += (xj[idx]=='0')*alpha*fj[idx]

        for a in range(fi+1):            
            sm = sm_base - a*dbeta
            
            if a == 0:
                constraints += [phi >= w[0]+w[1] - (1-alpha*fi)*(1-alpha*sm)-gamma*w[0]-gamma*w[1]*(1-alpha*fi)]

            constraints += [phi >= (1-alpha*fi)*(1-alpha*sm)+gamma*w[0]+gamma*w[1]*(1-alpha*fi) - w[0]-w[1]]
                    
problem = Problem(objective, constraints)
print("number of constraints: %d" %len(constraints))

number of constraints: 69122


In [7]:
result = problem.solve()
print("problem status: %s" %problem.status)
print("error: %0.4f" %problem.value)
print("weight(s): ")
print(w.value)

problem status: optimal
error: 0.4983
weight(s): 
[[9.96590617]
 [0.06818765]]


In [8]:
phi = Variable()
w = Variable(2)

objective = Minimize(phi)
constraints = []
# constraints += [w[0] == 0]

for i in [0,1,2]:
    for hi in range(5):
        for fi in range(5-hi):
            
            fj = {}
            for idx in range(4):
                fj[idx] = 0
        
            if hi == 0:
                fj_sum = 0
                
                for a in range(fi+1):
                    if a == 0:
                        constraints += [phi >= w[0]+w[1]*(i==0) -
                                       (i==0)*(1-alpha*fi)*(1-alpha*(alpha*fj_sum+fi*beta-a*dbeta)) -
                                       gamma*w[0]-gamma*w[1]*(i==0)*(1-alpha*fi)]
                    
                    constraints += [phi >= -w[0]-w[1]*(i==0) + 
                                    (i==0)*(1-alpha*fi)*(1-alpha*(alpha*fj_sum+fi*beta-a*dbeta)) + 
                                    gamma*w[0]+gamma*w[1]*(i==0)*(1-alpha*fi)]
                
            elif hi == 1:
                for fj_sum in range(4):
                    
                    for a in range(fi+1):      
                        if a == 0:
                            constraints += [phi >= w[0]+w[1]*(i==0) -
                                           (i==0)*(1-alpha*fi)*(1-alpha*(alpha*fj_sum+fi*beta-a*dbeta)) -
                                           gamma*w[0]-gamma*w[1]*(i==0)*(1-alpha*fi)]

                        constraints += [phi >= -w[0]-w[1]*(i==0) + 
                                        (i==0)*(1-alpha*fi)*(1-alpha*(alpha*fj_sum+fi*beta-a*dbeta)) + 
                                        gamma*w[0]+gamma*w[1]*(i==0)*(1-alpha*fi)]
                
            elif hi == 2:
                for c1 in range(4):
                    for c2 in range(4):
                        fj_sum = c1+c2
                        
                        for a in range(fi+1):      
                            if a == 0:
                                constraints += [phi >= w[0]+w[1]*(i==0) -
                                               (i==0)*(1-alpha*fi)*(1-alpha*(alpha*fj_sum+fi*beta-a*dbeta)) -
                                               gamma*w[0]-gamma*w[1]*(i==0)*(1-alpha*fi)]

                            constraints += [phi >= -w[0]-w[1]*(i==0) + 
                                            (i==0)*(1-alpha*fi)*(1-alpha*(alpha*fj_sum+fi*beta-a*dbeta)) + 
                                            gamma*w[0]+gamma*w[1]*(i==0)*(1-alpha*fi)]
                
            elif hi >= 3:
                 for k in range(2**8):
                    xk = np.base_repr(k, base=2).zfill(8)
                    fj[0] = xk[0:3].count('1')
                    fj[1] = xk[2:5].count('1')
                    fj[2] = xk[4:7].count('1')
                    fj[3] = xk[6:8].count('1') + (xk[0]=='1')
                    
                    fj_sum = sum(fj.values())
                    for a in range(fi+1):      
                        if a == 0:
                            constraints += [phi >= w[0]+w[1]*(i==0) -
                                           (i==0)*(1-alpha*fi)*(1-alpha*(alpha*fj_sum+fi*beta-a*dbeta)) -
                                           gamma*w[0]-gamma*w[1]*(i==0)*(1-alpha*fi)]

                        constraints += [phi >= -w[0]-w[1]*(i==0) + 
                                        (i==0)*(1-alpha*fi)*(1-alpha*(alpha*fj_sum+fi*beta-a*dbeta)) + 
                                        gamma*w[0]+gamma*w[1]*(i==0)*(1-alpha*fi)]    
                    
problem = Problem(objective, constraints)
print("number of constraints: %d" %len(constraints))

number of constraints: 6036


In [9]:
result = problem.solve()
print("problem status: %s" %problem.status)
print("error: %0.4f" %problem.value)
print("weight(s): ")
print(w.value)

problem status: optimal
error: 0.4983
weight(s): 
[[9.96590617]
 [0.06818765]]


### Second example

Basis functions: $v_{w} = \sum_{i=1}^{n} w_{1} + w_{2}\textbf{1}(x_{i}=H) + w_{3}\textbf{1}(x_{i}=H)\sum_{j\in N(i)}\textbf{1}(x_{j}=F)$

Reward: $R(x,a,x') = \sum_{i=1}^{n} \textbf{1}(x'_{i}=H)(1-\alpha f'_{i})$

In [17]:
phi = Variable()
w = Variable(3)
objective = Minimize(phi)
constraints = []

for i in [0,1,2]:
    for hi in range(5):
        for fi in range(5-hi):
            
            fj = {}
            for idx in range(4):
                fj[idx] = 0
            
            if hi == 0:
                fj_sum = 0
                for a in range(fi+1):
                    
                    if a == 0:
                        constraints += [phi >= w[0]+w[1]*(i==0)+w[2]*fi*(i==0) -
                                        (i==0)*(1-alpha*fi)*(1-alpha*(alpha*fj_sum+fi*beta-a*dbeta)) - 
                                        gamma*w[0]-gamma*w[1]*(i==0)*(1-alpha*fi) -
                                        gamma*w[2]*(alpha*fj_sum+fi*beta-a*dbeta)*(i==0)*(1-alpha*fi)]
                        
                    constraints += [phi >= -w[0]-w[1]*(i==0)-w[2]*fi*(i==0) +
                                    (i==0)*(1-alpha*fi)*(1-alpha*(alpha*fj_sum+fi*beta-a*dbeta)) +
                                    gamma*w[0]+gamma*w[1]*(i==0)*(1-alpha*fi) +
                                    gamma*w[2]*(alpha*fj_sum+fi*beta-a*dbeta)*(i==0)*(1-alpha*fi)]
                    
            elif hi == 1:
                for fj_sum in range(4):
                    for a in range(fi+1):
                        
                        if a == 0:
                            constraints += [phi >= w[0]+w[1]*(i==0)+w[2]*fi*(i==0) -
                                            (i==0)*(1-alpha*fi)*(1-alpha*(alpha*fj_sum+fi*beta-a*dbeta)) - 
                                            gamma*w[0]-gamma*w[1]*(i==0)*(1-alpha*fi) -
                                            gamma*w[2]*(alpha*fj_sum+fi*beta-a*dbeta)*(i==0)*(1-alpha*fi)]

                        constraints += [phi >= -w[0]-w[1]*(i==0)-w[2]*fi*(i==0) +
                                        (i==0)*(1-alpha*fi)*(1-alpha*(alpha*fj_sum+fi*beta-a*dbeta)) +
                                        gamma*w[0]+gamma*w[1]*(i==0)*(1-alpha*fi) +
                                        gamma*w[2]*(alpha*fj_sum+fi*beta-a*dbeta)*(i==0)*(1-alpha*fi)]       
                
            elif hi == 2:
                for c1 in range(4):
                    for c2 in range(4):
                        fj_sum = c1 + c2
                        
                        for a in range(fi+1):
                            if a == 0:
                                constraints += [phi >= w[0]+w[1]*(i==0)+w[2]*fi*(i==0) -
                                                (i==0)*(1-alpha*fi)*(1-alpha*(alpha*fj_sum+fi*beta-a*dbeta)) - 
                                                gamma*w[0]-gamma*w[1]*(i==0)*(1-alpha*fi) -
                                                gamma*w[2]*(alpha*fj_sum+fi*beta-a*dbeta)*(i==0)*(1-alpha*fi)]

                            constraints += [phi >= -w[0]-w[1]*(i==0)-w[2]*fi*(i==0) +
                                            (i==0)*(1-alpha*fi)*(1-alpha*(alpha*fj_sum+fi*beta-a*dbeta)) +
                                            gamma*w[0]+gamma*w[1]*(i==0)*(1-alpha*fi) +
                                            gamma*w[2]*(alpha*fj_sum+fi*beta-a*dbeta)*(i==0)*(1-alpha*fi)]
            elif hi >= 3:
                for k in range(2**8):
                    xk = np.base_repr(k, base=2).zfill(8)
                    fj[0] = xk[0:3].count('1')
                    fj[1] = xk[2:5].count('1')
                    fj[2] = xk[4:7].count('1')
                    fj[3] = xk[6:8].count('1') + (xk[0]=='1')
                    fj_sum = sum(fj.values())
                    
                    for a in range(fi+1):
                        if a == 0:
                            constraints += [phi >= w[0]+w[1]*(i==0)+w[2]*fi*(i==0) -
                                            (i==0)*(1-alpha*fi)*(1-alpha*(alpha*fj_sum+fi*beta-a*dbeta)) - 
                                            gamma*w[0]-gamma*w[1]*(i==0)*(1-alpha*fi) -
                                            gamma*w[2]*(alpha*fj_sum+fi*beta-a*dbeta)*(i==0)*(1-alpha*fi)]

                        constraints += [phi >= -w[0]-w[1]*(i==0)-w[2]*fi*(i==0) +
                                        (i==0)*(1-alpha*fi)*(1-alpha*(alpha*fj_sum+fi*beta-a*dbeta)) +
                                        gamma*w[0]+gamma*w[1]*(i==0)*(1-alpha*fi) +
                                        gamma*w[2]*(alpha*fj_sum+fi*beta-a*dbeta)*(i==0)*(1-alpha*fi)]

problem = Problem(objective, constraints)
print("number of constraints: %d" %len(constraints))                    

number of constraints: 6036


In [18]:
result = problem.solve()
print("problem status: %s" %problem.status)
print("error: %0.4f" %problem.value)
print("weight(s): ")
print(w.value)

problem status: optimal
error: 0.4878
weight(s): 
[[ 9.75688137]
 [ 0.48623725]
 [-0.10222953]]


### 3rd example

Basis functions: $v_{w}(x) = \sum_{i=1}^{n} w_{1} + w_{2}\textbf{1}(x_{i}=H) + w_{3}\textbf{1}(x_{i}=H)\sum_{j\in N(i)} \textbf{1}(x_{j}=H)$

Reward: $R(x,a,x')= \sum_{i=1}^{n} \textbf{1}(x'_{i} = H)(1-\alpha f'_{i})$

In [12]:
phi = Variable()
w = Variable(3)

objective = Minimize(phi)
constraints = []

for i in [0,1,2]:
    for hi in range(5):
        for fi in range(5-hi):
            
            fj = {}
            for idx in range(4):
                fj[idx] = 0
            
            if hi == 0:
                fj_sum = 0
                for a in range(fi+1):
                    
                    if a == 0:
                        constraints += [phi >= w[0]+w[1]*(i==0)+w[2]*hi*(i==0) -
                                        (i==0)*(1-alpha*fi)*(1-alpha*(alpha*fj_sum+fi*beta-a*dbeta)) - 
                                        gamma*w[0]-gamma*w[1]*(i==0)*(1-alpha*fi) -
                                        gamma*w[2]*(hi-alpha*fj_sum)*(i==0)*(1-alpha*fi)]
                        
                    constraints += [phi >= -w[0]-w[1]*(i==0)-w[2]*fi*(i==0) +
                                    (i==0)*(1-alpha*fi)*(1-alpha*(alpha*fj_sum+fi*beta-a*dbeta)) +
                                    gamma*w[0]+gamma*w[1]*(i==0)*(1-alpha*fi) +
                                    gamma*w[2]*(hi-alpha*fj_sum)*(i==0)*(1-alpha*fi)]
                    
            elif hi == 1:
                for fj_sum in range(4):
                    for a in range(fi+1):
                        
                        if a == 0:     
                            constraints += [phi >= w[0]+w[1]*(i==0)+w[2]*hi*(i==0) -
                                        (i==0)*(1-alpha*fi)*(1-alpha*(alpha*fj_sum+fi*beta-a*dbeta)) - 
                                        gamma*w[0]-gamma*w[1]*(i==0)*(1-alpha*fi) -
                                        gamma*w[2]*(hi-alpha*fj_sum)*(i==0)*(1-alpha*fi)]
                        
                        constraints += [phi >= -w[0]-w[1]*(i==0)-w[2]*fi*(i==0) +
                                        (i==0)*(1-alpha*fi)*(1-alpha*(alpha*fj_sum+fi*beta-a*dbeta)) +
                                        gamma*w[0]+gamma*w[1]*(i==0)*(1-alpha*fi) +
                                        gamma*w[2]*(hi-alpha*fj_sum)*(i==0)*(1-alpha*fi)]
                
            elif hi == 2:
                for c1 in range(4):
                    for c2 in range(4):
                        fj_sum = c1 + c2
                        
                        for a in range(fi+1):
                            if a == 0:
                                constraints += [phi >= w[0]+w[1]*(i==0)+w[2]*hi*(i==0) -
                                            (i==0)*(1-alpha*fi)*(1-alpha*(alpha*fj_sum+fi*beta-a*dbeta)) - 
                                            gamma*w[0]-gamma*w[1]*(i==0)*(1-alpha*fi) -
                                            gamma*w[2]*(hi-alpha*fj_sum)*(i==0)*(1-alpha*fi)]

                            constraints += [phi >= -w[0]-w[1]*(i==0)-w[2]*fi*(i==0) +
                                            (i==0)*(1-alpha*fi)*(1-alpha*(alpha*fj_sum+fi*beta-a*dbeta)) +
                                            gamma*w[0]+gamma*w[1]*(i==0)*(1-alpha*fi) +
                                            gamma*w[2]*(hi-alpha*fj_sum)*(i==0)*(1-alpha*fi)]


            elif hi >= 3:
                for k in range(2**8):
                    xk = np.base_repr(k, base=2).zfill(8)
                    fj[0] = xk[0:3].count('1')
                    fj[1] = xk[2:5].count('1')
                    fj[2] = xk[4:7].count('1')
                    fj[3] = xk[6:8].count('1') + (xk[0]=='1')
                    fj_sum = sum(fj.values())
                    
                    for a in range(fi+1):
                        if a == 0:
                            constraints += [phi >= w[0]+w[1]*(i==0)+w[2]*hi*(i==0) -
                                            (i==0)*(1-alpha*fi)*(1-alpha*(alpha*fj_sum+fi*beta-a*dbeta)) - 
                                            gamma*w[0]-gamma*w[1]*(i==0)*(1-alpha*fi) -
                                            gamma*w[2]*(hi-alpha*fj_sum)*(i==0)*(1-alpha*fi)]

                        constraints += [phi >= -w[0]-w[1]*(i==0)-w[2]*fi*(i==0) +
                                        (i==0)*(1-alpha*fi)*(1-alpha*(alpha*fj_sum+fi*beta-a*dbeta)) +
                                        gamma*w[0]+gamma*w[1]*(i==0)*(1-alpha*fi) +
                                        gamma*w[2]*(hi-alpha*fj_sum)*(i==0)*(1-alpha*fi)]


problem = Problem(objective, constraints)
print("number of constraints: %d" %len(constraints)) 

number of constraints: 6036


In [13]:
result = problem.solve()
print("problem status: %s" %problem.status)
print("error: %0.4f" %problem.value)
print("weight(s): ")
print(w.value)

problem status: optimal
error: 0.4983
weight(s): 
[[ 9.96590617]
 [ 0.06818765]
 [-0.13659291]]


In [14]:
phi = Variable()
w1 = Variable()
w2 = Variable()
o = Variable()

objective = Minimize(phi)
constraints = []
constraints += [phi >= 0]
constraints += [phi >=  gamma*o - o]
constraints += [phi >= -gamma*o + o]

for i in [0,1,2]:
    if i == 0:
        for j in range(3**4):
            xj = np.base_repr(j, base=3).zfill(4)
            fi = xj.count('1')
            hi = xj.count('0')
            
            fj = {}
            for idx in range(4):
                fj[idx] = 0
                
            for u in range(fi+1):
                if hi == 0:
                    fj_sum = 0
                    constraints += [phi >=  (1-alpha*fi)*(1-(alpha**2)*fj_sum-alpha*fi*beta+alpha*u*dbeta) + 
                                    gamma*w1*(1-alpha*fi) + gamma*w2*hi - gamma*alpha*w2*fj_sum + gamma*o - w1 - w2*hi - o]
                    if u == 0:
                        constraints += [phi >= -(1-alpha*fi)*(1-(alpha**2)*fj_sum-alpha*fi*beta+alpha*0*dbeta) - 
                                        gamma*w1*(1-alpha*fi) - gamma*w2*hi + gamma*alpha*w2*fj_sum - gamma*o + w1 + w2*hi + o]
                
                if hi == 1:
                    for cnt in range(5):
                        fj[0] = cnt
                        
                        fj_sum = sum(fj.values())
                        constraints += [phi >=  (1-alpha*fi)*(1-(alpha**2)*fj_sum-alpha*fi*beta+alpha*u*dbeta) + 
                                        gamma*w1*(1-alpha*fi) + gamma*w2*hi - gamma*alpha*w2*fj_sum + gamma*o - w1 - w2*hi - o]
                        if u == 0:
                            constraints += [phi >= -(1-alpha*fi)*(1-(alpha**2)*fj_sum-alpha*fi*beta+alpha*0*dbeta) - 
                                            gamma*w1*(1-alpha*fi) - gamma*w2*hi + gamma*alpha*w2*fj_sum - gamma*o + w1 + w2*hi + o]
                        
                elif hi == 2:
                    for cnt1 in range(5):
                        fj[0] = cnt1
                        for cnt2 in range(5):
                            fj[1] = cnt2    

                            fj_sum = sum(fj.values())
                            constraints += [phi >=  (1-alpha*fi)*(1-(alpha**2)*fj_sum-alpha*fi*beta+alpha*u*dbeta) + 
                                            gamma*w1*(1-alpha*fi) + gamma*w2*hi - gamma*alpha*w2*fj_sum + gamma*o - w1 - w2*hi - o]
                            if u == 0:
                                constraints += [phi >= -(1-alpha*fi)*(1-(alpha**2)*fj_sum-alpha*fi*beta+alpha*0*dbeta) - 
                                                gamma*w1*(1-alpha*fi) - gamma*w2*hi + gamma*alpha*w2*fj_sum - gamma*o + w1 + w2*hi + o]

                elif hi == 3:
                    for k in range(2**8):
                        xk = np.base_repr(k, base=2).zfill(8)
                        fj[0] = xk[0:3].count('1')
                        fj[1] = xk[2:5].count('1')
                        fj[2] = xk[4:7].count('1')

                        fj_sum = sum(fj.values())
                        constraints += [phi >=  (1-alpha*fi)*(1-(alpha**2)*fj_sum-alpha*fi*beta+alpha*u*dbeta) + 
                                        gamma*w1*(1-alpha*fi) + gamma*w2*hi - gamma*alpha*w2*fj_sum + gamma*o - w1 - w2*hi - o]
                        if u == 0:
                            constraints += [phi >= -(1-alpha*fi)*(1-(alpha**2)*fj_sum-alpha*fi*beta+alpha*0*dbeta) - 
                                            gamma*w1*(1-alpha*fi) - gamma*w2*hi + gamma*alpha*w2*fj_sum - gamma*o + w1 + w2*hi + o]

                elif hi == 4:
                    for k in range(2**8):
                        xk = np.base_repr(k, base=2).zfill(8)
                        fj[0] = xk[0:3].count('1')
                        fj[1] = xk[2:5].count('1')
                        fj[2] = xk[4:7].count('1')
                        fj[3] = xk[6:8].count('1') + xk[0].count('1')

                        fj_sum = sum(fj.values())
                        constraints += [phi >=  (1-alpha*fi)*(1-(alpha**2)*fj_sum-alpha*fi*beta+alpha*u*dbeta) + 
                                        gamma*w1*(1-alpha*fi) + gamma*w2*hi - gamma*alpha*w2*fj_sum + gamma*o - w1 - w2*hi - o]
                        if u == 0:
                            constraints += [phi >= -(1-alpha*fi)*(1-(alpha**2)*fj_sum-alpha*fi*beta+alpha*0*dbeta) - 
                                            gamma*w1*(1-alpha*fi) - gamma*w2*hi + gamma*alpha*w2*fj_sum - gamma*o + w1 + w2*hi + o]
        
    if i == 1 or i == 2:
        for j in range(3**4):
            xj = np.base_repr(j, base=3).zfill(4)
            fi = xj.count('1')
            hi = xj.count('0')
            
            fj = {}
            for idx in range(4):
                fj[idx] = 0
                
            if hi == 1:
                for cnt in range(4):
                    fj[0] = cnt + (i-1)

                    fj_sum = sum(fj.values())
                    constraints += [phi >=  gamma*w2*hi - gamma*alpha*w2*fj_sum + gamma*o - w2*hi - o]
                    constraints += [phi >= -gamma*w2*hi + gamma*alpha*w2*fj_sum - gamma*o + w2*hi + o]

            elif hi == 2:
                for cnt1 in range(4):
                    fj[0] = cnt1 + (i-1)
                    for cnt2 in range(4):
                        fj[1] = cnt2 + (i-1)

                        fj_sum = sum(fj.values())
                        constraints += [phi >=  gamma*w2*hi - gamma*alpha*w2*fj_sum + gamma*o - w2*hi - o]
                        constraints += [phi >= -gamma*w2*hi + gamma*alpha*w2*fj_sum - gamma*o + w2*hi + o]

            elif hi == 3:
                for k in range(2**3):
                    xk = np.base_repr(k, base=2).zfill(8)
                    fj[0] = xk[0:3].count('1') + (i-1)
                    fj[1] = xk[2:5].count('1') + (i-1)
                    fj[2] = xk[4:7].count('1') + (i-1)

                    fj_sum = sum(fj.values())
                    constraints += [phi >=  gamma*w2*hi - gamma*alpha*w2*fj_sum + gamma*o - w2*hi - o]
                    constraints += [phi >= -gamma*w2*hi + gamma*alpha*w2*fj_sum - gamma*o + w2*hi + o]

            elif hi == 4:
                for k in range(2**4):
                    xk = np.base_repr(k, base=2).zfill(8)
                    fj[0] = xk[0:3].count('1') + (i-1)
                    fj[1] = xk[2:5].count('1') + (i-1)
                    fj[2] = xk[4:7].count('1') + (i-1)
                    fj[3] = xk[6:8].count('1') + xk[0].count('1') + (i-1)

                    fj_sum = sum(fj.values())
                    constraints += [phi >=  gamma*w2*hi - gamma*alpha*w2*fj_sum + gamma*o - w2*hi - o]
                    constraints += [phi >= -gamma*w2*hi + gamma*alpha*w2*fj_sum - gamma*o + w2*hi + o]        

problem = Problem(objective, constraints)
print("number of constraints: %d" %len(constraints))

number of constraints: 10427


In [16]:
result = problem.solve()
print("problem status: %s" %problem.status)
print("error: %0.4f" %problem.value)
print("weight(s): ")
print("%0.4f" %o.value)
print("%0.4f" %w1.value)
print("%0.4f" %w2.value)

problem status: optimal
error: 0.4983
weight(s): 
9.9659
0.0682
-0.0000


### fourth example

Reward $r_{i} = \textbf{1}_{H}(x_{i}^{t}) + \textbf{1}_{F}(x_{i}^{t})(1 - \beta + \Delta\beta a_{i}^{t})$

basis $w_{0} + w_{1}\textbf{1}_{H}(x_{i}^{t}) + w_{2}\textbf{1}_{F}(x_{i}^{t})\sum_{j\in N(i)}\textbf{1}_{H}(x_{j}^{t})$

In [34]:
phi = Variable()
w = Variable(3)
objective = Minimize(phi)
constraints = []

for i in [0,1,2]:
    if i == 0:
        for fi in range(5):
            constraints += [phi >= w[0] + w[1] -
                            1 -
                            gamma*w[0] - gamma*w[1]*(1-alpha*fi)]
            constraints += [phi >= -w[0] - w[1] +
                            1 +
                            gamma*w[0] + gamma*w[1]*(1-alpha*fi)]
            
    if i == 1:
        for ai in [0,1]:
            for hi in range(5):
                for k in range(2**(3*hi+(hi==3)*(-1)+(hi==4)*(-3))):
                    fj = {}
                    xk = np.base_repr(k, base=2).zfill(8)
                    fj[0] = xk[0:3].count('1')
                    fj[1] = xk[2:5].count('1')
                    fj[2] = xk[4:7].count('1')
                    fj[3] = xk[6:8].count('1') + (xk[0]=='1')
                    
                    isum = 0
                    for j in range(hi):
                        isum += (1-alpha*fj[j])

                    if ai == 0:
                        constraints += [phi >= w[0] + w[2]*hi -
                                        (1 - beta + dbeta*ai) - 
                                        gamma*w[0] - gamma*w[2]*(beta-dbeta*ai)*isum]
                        
                    constraints += [phi >= -w[0] - w[2]*hi +
                                    (1 - beta + dbeta*ai) + 
                                    gamma*w[0] + gamma*w[2]*(beta-dbeta*ai)*isum]
                    
    if i == 2:
        constraints += [phi >= w[0] - gamma*w[0]]
        constraints += [phi >= -w[0] + gamma*w[0]]
        
problem = Problem(objective, constraints)
print("number of constraints: %d" %len(constraints))

number of constraints: 2535


In [35]:
result = problem.solve()
print("problem status: %s" %problem.status)
print("error: %0.4f" %problem.value)
print("weight(s): ")
print(w.value)

problem status: optimal
error: 0.4691
weight(s): 
[[ 9.38271605]
 [ 1.2345679 ]
 [-0.03367766]]


### approximate Q function method

basis functions $w_{0} + w_{1}\textbf{1}_{H}(x_{i}^{t}) + w_{2}\textbf{1}_{F}(x_{i}^{t}) + w_{3}a_{i}^{t}\textbf{1}_{F}(x_{i}^{t})\sum_{j \in N(i)} \textbf{1}_{H}(x_{j}^{t})(1 - \alpha f_{j}^{t})$

reward $r_{i} = \textbf{1}_{H}(x_{i}^{t+1})(1-\alpha f_{i}^{t+1})$

In [25]:
phi = Variable()
w = Variable(4)
objective = Minimize(phi)
constraints = []

for i in [0,1,2]:
    if i == 0:
        
        for hi in range(5):
            for fi in range(5-hi):
                for fj_sum in range(3*hi+(hi==3)*(-1)+(hi==4)*(-3)):
                    for aj in range(fi+1):
                        constraints += [phi >= w[0] + w[1] -
                                        (1-alpha*fi)*(1-alpha*(alpha*fj_sum+fi*beta-aj*dbeta)) -
                                        gamma*w[0] - gamma*w[1]*(1-alpha*fi) - gamma*w[2]*alpha*fi]

                        constraints += [phi >= -w[0] - w[1] +
                                        (1-alpha*fi)*(1-alpha*(alpha*fj_sum+fi*beta-aj*dbeta)) +
                                        gamma*w[0] + gamma*w[1]*(1-alpha*fi) + gamma*w[2]*alpha*fi]

    elif i == 1:
        for ai in [0,1]:
            for hi in range(5):
                for k in range(2**(3*hi+(hi==3)*(-1)+(hi==4)*(-3))):
                    fj = {}
                    xk = np.base_repr(k, base=2).zfill(8)
                    fj[0] = xk[0:3].count('1')
                    fj[1] = xk[2:5].count('1')
                    fj[2] = xk[4:7].count('1')
                    fj[3] = xk[6:8].count('1') + (xk[0]=='1')
                    
                    smallsum = 0
                    bigsum = 0
                    for j in range(hi):
                        smallsum += (1-alpha*fj[j])
                        
                        if j == 0:
                            idxlist = [0,1,2]
                        elif j == 1:
                            idxlist = [2,3,4]
                        elif j == 2:
                            idxlist = [4,5,6]
                        elif j == 3:
                            idxlist = [6,7,0]
                        
                        for idx in idxlist:
                            if xk[idx] == '0':
                                for fk in range(5):
                                    bigsum += (1-alpha*fj[j])*(1-alpha*(1-alpha*fk))
                            else:
                                for ak in [0,1]:
                                    bigsum += (1-alpha*fj[j])*(1-alpha*(beta-dbeta*ak))
                                        
                    constraints += [phi >= w[0] + w[2] + w[3]*ai*smallsum -
                                    0 - 
                                    gamma*w[0] - gamma*w[2]*(beta - dbeta*ai)]

                    constraints += [phi >= -w[0] - w[2] - w[3]*ai*smallsum +
                                    0 + 
                                    gamma*w[0] + gamma*w[2]*(beta - dbeta*ai)]

                    constraints += [phi >= -w[0] - w[2] - w[3]*ai*smallsum +
                                    0 +
                                    gamma*w[0] + gamma*w[2]*(beta - dbeta*ai) +
                                    gamma*w[3]*(beta-dbeta*ai)*bigsum]
        
    elif i == 2:
        constraints += [phi >=  w[0] - gamma*w[0]]
        constraints += [phi >= -w[0] + gamma*w[0]]
        
problem = Problem(objective, constraints)
print("number of constraints: %d" %len(constraints))

number of constraints: 5246


In [26]:
result = problem.solve()
print("problem status: %s" %problem.status)
print("error: %0.4f" %problem.value)
print("weight(s): ")
print(w.value)

problem status: optimal
error: 0.4587
weight(s): 
[[ 9.17487535]
 [ 1.65024929]
 [ 1.53036239]
 [-0.09904618]]


### forsell et al. basis functions

In [36]:
phi = Variable()
w = Variable(3)
objective = Minimize(phi)
constraints = []

for i in [0,1,2]:
    for hi in range(5):
        for fi in range(5-hi):
            
            fj = {}
            for idx in range(4):
                fj[idx] = 0
            
            if hi == 0:
                fj_sum = 0
                for a in range(fi+1):
                    
                    if a == 0:
                        constraints += [phi >= w[0]*(i==0)+w[1]*(i==1)+w[2]*(i==2) -
                                        (i==0)*(1-alpha*fi)*(1-alpha*(alpha*fj_sum+fi*beta-a*dbeta)) - 
                                        gamma*w[0]*(i==0)*(1-alpha*fi) -
                                        gamma*w[1]*(i==0)*(alpha*fi) -
                                        gamma*w[1]*(i==1)*(beta-dbeta*a) -
                                        gamma*w[2]*(i==1)*(1-beta+dbeta*a) -
                                        gamma*w[2]*(i==2)]
                        
                    constraints += [phi >= -w[0]*(i==0)-w[1]*(i==1)-w[2]*(i==2) +
                                    (i==0)*(1-alpha*fi)*(1-alpha*(alpha*fj_sum+i*beta-a*dbeta)) +
                                    gamma*w[0]*(i==0)*(1-alpha*fi) +
                                    gamma*w[1]*(i==0)*(alpha*fi) +
                                    gamma*w[1]*(i==1)*(beta-dbeta*a) +
                                    gamma*w[2]*(i==1)*(1-beta+dbeta*a) +
                                    gamma*w[2]*(i==2)]
                    
            elif hi == 1:
                for fj_sum in range(4):
                    for a in range(fi+1):
                        if a == 0:
                            constraints += [phi >= w[0]*(i==0)+w[1]*(i==1)+w[2]*(i==2) -
                                            (i==0)*(1-alpha*fi)*(1-alpha*(alpha*fj_sum+fi*beta-a*dbeta)) - 
                                            gamma*w[0]*(i==0)*(1-alpha*fi) -
                                            gamma*w[1]*(i==0)*(alpha*fi) -
                                            gamma*w[1]*(i==1)*(beta-dbeta*a) -
                                            gamma*w[2]*(i==1)*(1-beta+dbeta*a) -
                                            gamma*w[2]*(i==2)]

                        constraints += [phi >= -w[0]*(i==0)-w[1]*(i==1)-w[2]*(i==2) +
                                        (i==0)*(1-alpha*fi)*(1-alpha*(alpha*fj_sum+i*beta-a*dbeta)) +
                                        gamma*w[0]*(i==0)*(1-alpha*fi) +
                                        gamma*w[1]*(i==0)*(alpha*fi) +
                                        gamma*w[1]*(i==1)*(beta-dbeta*a) +
                                        gamma*w[2]*(i==1)*(1-beta+dbeta*a) +
                                        gamma*w[2]*(i==2)]     
                
            elif hi == 2:
                for c1 in range(4):
                    for c2 in range(4):
                        fj_sum = c1 + c2
                        
                        for a in range(fi+1):
                            if a == 0:
                                constraints += [phi >= w[0]*(i==0)+w[1]*(i==1)+w[2]*(i==2) -
                                                (i==0)*(1-alpha*fi)*(1-alpha*(alpha*fj_sum+fi*beta-a*dbeta)) - 
                                                gamma*w[0]*(i==0)*(1-alpha*fi) -
                                                gamma*w[1]*(i==0)*(alpha*fi) -
                                                gamma*w[1]*(i==1)*(beta-dbeta*a) -
                                                gamma*w[2]*(i==1)*(1-beta+dbeta*a) -
                                                gamma*w[2]*(i==2)]

                            constraints += [phi >= -w[0]*(i==0)-w[1]*(i==1)-w[2]*(i==2) +
                                            (i==0)*(1-alpha*fi)*(1-alpha*(alpha*fj_sum+i*beta-a*dbeta)) +
                                            gamma*w[0]*(i==0)*(1-alpha*fi) +
                                            gamma*w[1]*(i==0)*(alpha*fi) +
                                            gamma*w[1]*(i==1)*(beta-dbeta*a) +
                                            gamma*w[2]*(i==1)*(1-beta+dbeta*a) +
                                            gamma*w[2]*(i==2)]
            elif hi >= 3:
                for k in range(2**8):
                    xk = np.base_repr(k, base=2).zfill(8)
                    fj[0] = xk[0:3].count('1')
                    fj[1] = xk[2:5].count('1')
                    fj[2] = xk[4:7].count('1')
                    fj[3] = xk[6:8].count('1') + (xk[0]=='1')
                    fj_sum = sum(fj.values())
                    
                    for a in range(fi+1):
                        if a == 0:
                            constraints += [phi >= w[0]*(i==0)+w[1]*(i==1)+w[2]*(i==2) -
                                            (i==0)*(1-alpha*fi)*(1-alpha*(alpha*fj_sum+fi*beta-a*dbeta)) - 
                                            gamma*w[0]*(i==0)*(1-alpha*fi) -
                                            gamma*w[1]*(i==0)*(alpha*fi) -
                                            gamma*w[1]*(i==1)*(beta-dbeta*a) -
                                            gamma*w[2]*(i==1)*(1-beta+dbeta*a) -
                                            gamma*w[2]*(i==2)]

                        constraints += [phi >= -w[0]*(i==0)-w[1]*(i==1)-w[2]*(i==2) +
                                        (i==0)*(1-alpha*fi)*(1-alpha*(alpha*fj_sum+i*beta-a*dbeta)) +
                                        gamma*w[0]*(i==0)*(1-alpha*fi) +
                                        gamma*w[1]*(i==0)*(alpha*fi) +
                                        gamma*w[1]*(i==1)*(beta-dbeta*a) +
                                        gamma*w[2]*(i==1)*(1-beta+dbeta*a) +
                                        gamma*w[2]*(i==2)]

problem = Problem(objective, constraints)
print("number of constraints: %d" %len(constraints))                    

number of constraints: 6036


In [37]:
result = problem.solve()
print("problem status: %s" %problem.status)
print("error: %0.4f" %problem.value)
print("weight(s): ")
print(w.value)

problem status: optimal
error: 0.4983
weight(s): 
[[10.03409383]
 [ 9.96590617]
 [ 9.96590617]]


Reward $r_{i} = \textbf{1}_{H}(x_{i}^{t}) + \textbf{1}_{F}(x_{i}^{t})(1 - \beta + \Delta\beta a_{i}^{t})$

In [52]:
phi = Variable()
w = Variable(3)
objective = Minimize(phi)
constraints = []

for i in [0,1,2]:
    if i == 0:
        for fi in range(5):
            constraints += [phi >= w[0] -
                            1 -
                            gamma*w[0]*(1-alpha*fi) - gamma*w[1]*alpha*fi]

            constraints += [phi >= w[0] +
                            1 +
                            gamma*w[0]*(1-alpha*fi) + gamma*w[1]*alpha*fi]
        
    elif i == 1:
        for ai in [0,1]:
            constraints += [phi >= w[1] -
                            (1-beta+dbeta*ai) -
                            gamma*w[1]*(beta-dbeta*ai) - gamma*w[2]*(1-beta+dbeta*ai)]

            constraints += [phi >= w[1] +
                            (1-beta+dbeta*ai) +
                            gamma*w[1]*(beta-dbeta*ai) + gamma*w[2]*(1-beta+dbeta*ai)]
        
    elif i == 2:
        constraints += [phi >= w[2] - gamma*w[2]]
        constraints += [phi >= -w[2] + gamma*w[2]]

problem = Problem(objective, constraints)
print("number of constraints: %d" %len(constraints))      

number of constraints: 16


In [53]:
result = problem.solve()
print("problem status: %s" %problem.status)
print("error: %0.4f" %problem.value)
print("weight(s): ")
print(w.value)

problem status: optimal
error: -0.0000
weight(s): 
[[-1.02949270e+00]
 [-1.07226902e+00]
 [ 4.75769649e-10]]
